## 一、语法

### 1. tensor创建

tensor: 是PyTorch中最基本的数据结构，类似于numpy中的ndarray。tensor可以在GPU上进行计算。通常为数值型数据，支持多维数组。

In [1]:
import torch

x = torch.tensor([1,2,3])   #创建[1,2,3]的一维tensor
x = torch.randn(2,3)        #创建2行3列的随机tensor
x = torch.zeros(2,3)        #创建2行3列的全零tensor
x = torch.ones(2,3)         #创建2行3列的全一tensor

torch.arange(10)            #创建一个从0到9的一维tensor
torch.arange(0, 10, 2)      #创建一个从0到9的步长为2的一维tensor

torch.eye(4)                #创建一个4行4列的单位矩阵tensor

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### 2. shape操作

1. reshape: 改变tensor的形状，返回一个新的tensor，原tensor不变。

In [ ]:
x = torch.randn(2,3,4)  # 创建一个2行3列4通道的随机tensor

x.view(6,4)             # tensor是连续的
x.reshape(6,4)          # 如果无法返回 view，则自动创建新的连续张量并复制数据。

tensor([[ 0.2420, -0.5338,  0.6984,  1.3556],
        [ 0.7334,  1.0488,  1.2854,  0.0896],
        [-1.6656, -0.1524, -0.1854,  0.9936],
        [ 1.4523,  1.3246, -0.5963, -0.4986],
        [-0.1186, -1.2081, -1.2410,  0.0822],
        [ 0.6687, -0.4423,  1.3978, -0.1723]])

2. transpose

In [ ]:
x.transpose(1,2)    #转置tensor的维度，(1,2)表示将第1维和第2维交换位置

tensor([[[ 0.2420,  0.7334, -1.6656],
         [-0.5338,  1.0488, -0.1524],
         [ 0.6984,  1.2854, -0.1854],
         [ 1.3556,  0.0896,  0.9936]],

        [[ 1.4523, -0.1186,  0.6687],
         [ 1.3246, -1.2081, -0.4423],
         [-0.5963, -1.2410,  1.3978],
         [-0.4986,  0.0822, -0.1723]]])

In [ ]:
Q = Q.view(B,S,H,d_k).transpose(1,2)

# (B,S,H,d_k)
# ->
# (B,H,S,d_k)
# B: batch size
# S: sequence length
# H: number of heads
# B保持不变是因为(1,2)表示将第1维和第2维交换位置，B是第0维，所以不变

3. contiguous: 返回一个连续的tensor，如果原tensor是连续的，则返回原tensor，否则返回一个新的连续tensor。

In [ ]:
x = x.transpose(1,2)

x = x.contiguous().view(...) #transpose 后内存不连续。

4. unsqueeze 
在指定位置插入一个维度为1的维度，返回一个新的tensor，原tensor不变。

In [13]:
x = torch.randn(10)
print(x.unsqueeze(0).shape)  # (1,10)


torch.Size([1, 10])


In [ ]:
x = torch.randn(10)

x.unsqueeze(0)
# (1,10)



tensor([[-0.0927, -0.9336,  1.6841, -1.7814, -0.8100, -0.4195, -0.3198,  0.2109,
         -0.4168,  0.1024]])

In [11]:
x.unsqueeze(1)
# (10,1)

tensor([[-0.0927],
        [-0.9336],
        [ 1.6841],
        [-1.7814],
        [-0.8100],
        [-0.4195],
        [-0.3198],
        [ 0.2109],
        [-0.4168],
        [ 0.1024]])

### RoPE

给张量增加维度，以便利用 broadcasting（广播机制） 计算位置编码。

In [ ]:
# q.shape = [batch, seq_len, num_heads, head_dim]

q.shape = [2, 4, 8, 64]
freqs.shape = [seq_len, head_dim/2]

In [15]:
freqs = torch.randn(10)
freqs.unsqueeze(0).unsqueeze(2)

tensor([[[-1.5270],
         [-0.0191],
         [ 0.9386],
         [-1.8102],
         [ 1.7382],
         [ 0.1490],
         [ 2.6379],
         [-0.1321],
         [ 0.6388],
         [ 1.4932]]])

5. squeeze

In [16]:
#删除长度为1的维度
x.squeeze()  

tensor([ 0.0695,  0.3308, -0.1661, -0.3361, -0.1008, -0.8053, -0.2827, -1.4107,
         1.2211, -0.6691])

6. cat

arg1: tensor列表，要求所有tensor的shape除了指定的维度外，其余维度必须相同。
arg2: 指定的维度。

In [19]:
K = torch.randn(2,3,4)
V = torch.randn(2,3,4)
K_prev = torch.randn(2,3,4)
V_prev = torch.randn(2,3,4)

K = torch.cat([K_prev, K], dim=2)
V = torch.cat([V_prev, V], dim=2)
print(K.shape)  # (2,3,8)
print(V.shape)  # (2,3,8)

torch.Size([2, 3, 8])
torch.Size([2, 3, 8])


## 数学计算API

1. softmax

In [22]:
import torch.nn.functional as F
x = torch.tensor([[2.0, 1.0, 0.1], [1.0, 2.0, 3.0]])
F.softmax(x, dim=-1)    # sim = -1: 指定在最后一个维度上进行softmax计算

tensor([[0.6590, 0.2424, 0.0986],
        [0.0900, 0.2447, 0.6652]])

2. sigmoid,silu,etc.

In [ ]:
torch.sigmoid(x) #sigmoid函数

tensor([[0.8808, 0.7311, 0.5250],
        [0.7311, 0.8808, 0.9526]])

In [ ]:
x * torch.sigmoid(x) # silu函数

In [ ]:
F.gelu(x)

In [ ]:
F.logsigmoid(x) #DPO loss中使用的logsigmoid函数

3. layernorm

layernorm: mean和std计算公式：


In [24]:
# mean
x.mean(dim=-1)

tensor([1.0333, 2.0000])

In [26]:
mu = x.mean(dim=-1, keepdim=True)

print(mu)  # (2,1)

tensor([[1.0333],
        [2.0000]])
